using Api.Main;
using Api.Security;
using Api.DTOs;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Text;
using Api.ActivityLogModule;
using Api.CartModule;
using Api.CategoriesModule;
using Api.MedicineModule;
using Api.OrderModule;
using Api.UserModule;
using Api.UserRoleModule;

var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddInMemoryCollection(ConnEnvFile.LoadConfigurationValues());

// Startup environment safety check
using (var loggerFactory = LoggerFactory.Create(b => b.AddConsole()))
{
    var startupLogger = loggerFactory.CreateLogger("Startup");
    var env = builder.Environment.EnvironmentName;
    if (string.IsNullOrWhiteSpace(env))
        startupLogger.LogWarning("ASPNETCORE_ENVIRONMENT is not set. Defaulting to Production behavior. Ensure this is intentional.");
    else
        startupLogger.LogInformation("Running in environment: {Environment}", env);
}

// Add services to the container.
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters.Add(new RegisterRequestJsonConverter());
    });

// Configure Swagger/OpenAPI
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo
    {
        Version = "v1",
        Title = "Generated API",
        Description = "API generated by Lance Code Studio"
    });

    // Add JWT Bearer authentication to Swagger
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = @"JWT Authorization header using the Bearer scheme.
                      Enter 'Bearer' [space] and then your token in the text input below.
                      Example: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        Extensions =
    {
        ["x-example"] = new OpenApiString(
            "Bearer A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C"
        )
    }
    });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

// Configure JWT Authentication
string jwtKey = JwtConfiguration.ResolveSigningKey(builder.Configuration, builder.Environment);

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? JwtConfiguration.DefaultIssuer,
        ValidAudience = builder.Configuration["Jwt:Audience"] ?? JwtConfiguration.DefaultAudience,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
    };
});

// Configure Authorization Policies
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("AdminAccess", policy => policy.RequireClaim("user_role_id", "1"));
    options.AddPolicy("ModAccess", policy => policy.RequireClaim("user_role_id", new[] { "1", "2" }));
    options.AddPolicy("UserAccess", policy => policy.RequireClaim("user_role_id", new[] { "1", "2", "3" }));
});

builder.Services.AddScoped<MyCon>(_ => new MyCon());

// Register generated repositories for all entities.
// Expected model shape:
// - entities: [{ entity_name, module_name }, ...]
//   or
// - modules: [{ module_name, entities: [{ entity_name }, ...] }, ...]
// User module
builder.Services.AddScoped<IUserRepository, UserRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    return new UserRepository(myCon);
});

// UserRole module
builder.Services.AddScoped<IUserroleRepository, UserroleRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    return new UserroleRepository(myCon);
});

// Medicine module
builder.Services.AddScoped<IMedicineRepository, MedicineRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    return new MedicineRepository(myCon);
});

// Order module
builder.Services.AddScoped<IOrderItemRepository, OrderItemRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    return new OrderItemRepository(myCon);
});
builder.Services.AddScoped<IOrderRepository, OrderRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    var itemRepo = sp.GetRequiredService<IOrderItemRepository>();
    return new OrderRepository(myCon, itemRepo);
});

// Register JWT Token Service
builder.Services.AddScoped<IJwtTokenService, JwtTokenService>();

// ActivityLog module
builder.Services.AddScoped<IActivityLogRepository, ActivityLogRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    return new ActivityLogRepository(myCon);
});

// Cart module
builder.Services.AddScoped<ICartRepository, CartRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    return new CartRepository(myCon);
});

// Categories module
builder.Services.AddScoped<ICategoryRepository, CategoryRepository>(sp =>
{
    var myCon = sp.GetRequiredService<MyCon>();
    return new CategoryRepository(myCon);
});

var configuredCorsOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()?
    .Where(origin => !string.IsNullOrWhiteSpace(origin))
    .Select(origin => origin.Trim().TrimEnd('/'))
    .Distinct(StringComparer.OrdinalIgnoreCase)
    .ToArray() ?? Array.Empty<string>();

builder.Services.AddCors(options =>
{
    options.AddPolicy("ConfiguredOrigins", policy =>
    {
        if (configuredCorsOrigins.Length == 0)
        {
            // Fail closed when no origin is configured.
            policy.SetIsOriginAllowed(_ => false)
                .AllowAnyMethod()
                .AllowAnyHeader();
            return;
        }

        policy.WithOrigins(configuredCorsOrigins)
            .AllowAnyMethod()
            .AllowAnyHeader();
    });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
app.UseHttpsRedirection();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint($"/swagger/v1/swagger.json", "Generated API V1");
        options.RoutePrefix = string.Empty;
    });
}
app.UseAuthentication();
app.UseAuthorization();
app.UseCors("ConfiguredOrigins");
app.MapControllers();

// Add health check endpoint
app.MapGet("/health", () => Results.Ok(new { status = "healthy", timestamp = DateTime.UtcNow }));

// Add database connection test endpoint
// NOTE: This endpoint is unauthenticated. Consider removing or auth-gating it for production builds.
app.MapGet("/db-test", async (MyCon db, ILogger<Program> logger) =>
{
    try
    {
        var canConnect = await db.CanConnectAsync();
        if (canConnect)
        {
            return Results.Ok(new
            {
                status = "Database connection successful",
                timestamp = DateTime.UtcNow
            });
        }
        else
        {
            return Results.Problem("Database connection failed");
        }
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Database connection test failed");
        return Results.Problem(
            detail: "Database connection error",
            statusCode: 500,
            title: "Database connection error"
        );
    }
});

app.Run();

public partial class Program
{
}